raw_flight_training = {
    'id':'INT',
    'Account':'BIGINT',
    'Borrower':'VARCHAR(50)',
    'Name':'VARCHAR(50)',
    'Date of Loan Application':'DATE',
    'FIRST NAME':'VARCHAR(50)',
    'LAST NAME':'VARCHAR(50)',
    'ADDRESS LINE 1':'VARCHAR(225)',
    'CITY':'VARCHAR(50)',
    'STATE/ REGION':'VARCHAR(50)',
    'POSTAL CODE':'BIGINT',
    'CITIZENSHIP':'VARCHAR(50)',
    'COUNTRY':'VARCHAR(50)',
    'EMAIL ADD':'VARCHAR(50)',
    'PHONE':'VARCHAR(50)',
    'BIRTHDAY':'DATE',
    'School':'VARCHAR(225)',
    'NPS':'VARCHAR(5)',
    'Flight School State':'VARCHAR(5)',
    'Flight School Tier':'VARCHAR(50)',
    'Part 141 or 61 or Both':'VARCHAR(50)',
    'Program':'TEXT',
    'Particulars':'VARCHAR(50)',
    'Loan Amount':'DOUBLE',
    'Total Hours':'INT',
    '0 hours':'DATE',
    '40/50 hours':'DATE',
    '70/120 hours':'DATE',
    '170/180 hours':'DATE',
    '200/220 hours':'DATE',
    '230 hours':'DATE',
    'succeeding funding':'VARCHAR(45)',
    'No. of Months':'VARCHAR(5)',
    'Funding Status':'VARCHAR(50)',
    'Date of Last Funding':'DATE',
    'Has been 6 months or more since DATE completed':'INT',
    'Inactive for 3 months':'INT',
    'Inactive for 6 months':'INT',
    'School if borrower transfered school':'VARCHAR(225)',
    'Date of Transfer':'DATETIME',
    'Reason':'VARCHAR(225)',
    'Medical Class':'VARCHAR(50)',
    'Date of Medical Exam':'DATETIME',
    'PPL':'VARCHAR(5)',
    'IFR':'VARCHAR(5)',
    'COMM SE':'VARCHAR(5)',
    'COMM Multi':'VARCHAR(5)',
    'CFI':'VARCHAR(5)',
    'CFII':'VARCHAR(5)',
    'MEI':'VARCHAR(5)',
    'ATP':'VARCHAR(5)',
    'Type Rated':'INT',
    'Certificate Number':'BIGINT',
    'Certificates based on FAA':'TEXT',
    'Other Certificates based on FAA':'VARCHAR(225)',
    'Date latest Cert was issued by FAA':'DATETIME',
    'Date Last Update from FAA':'DATETIME',
    'Date of Follow-up':'DATETIME',
    'Remarks':'TEXT',
    'Employment':'VARCHAR(225)',
    'Contact Number':'VARCHAR(50)',
    'Last UpDATE':'VARCHAR(50)',
    'Name or other searching critera used on FAA website':'TEXT',
    'Updated School':'VARCHAR(50)'
}