stg_school_funding_xero = {
    'id':'INT',
    'Account':'BIGINT',
    'Student Name':'VARCHAR(50)',
    'Funding Status':'VARCHAR(50)',
    'months since max':'int',
    'months':'int',
    'min':'DATETIME',
    'max':'DATETIME',
    'Payment Date 1':'DATETIME',
    'Payment Date 2':'DATETIME',
    'Payment Date 3':'DATETIME',
    'Payment Date 4':'DATETIME',
    'Payment Date 5':'DATETIME',
    'Payment Date 6':'DATETIME',
    'Payment Date 7':'DATETIME',
    'Payment Date 8':'DATETIME',
    'Payment Date 9':'DATETIME',
    'Payment Date 10':'DATETIME',
    'Payment Date 11':'DATETIME',
    'Payment Date 12':'DATETIME',
    'Payment Date 13':'DATETIME',
    'Payment Date 14':'DATETIME',
    'Payment Date 15':'DATETIME',
    'Payment Date 16':'DATETIME',
    'Payment Date 17':'DATETIME',
    'Payment Date 18':'DATETIME',
    'Payment Date 19':'DATETIME',
    'Payment Date 20':'DATETIME',
    'Payment Date 21':'DATETIME',
    'Flight School 1':'VARCHAR(255)',
    'Flight School 2':'VARCHAR(255)',
    'Flight School 3':'VARCHAR(255)',
    'Flight School 4':'VARCHAR(255)',
    'Flight School 5':'VARCHAR(255)',
    'Flight School 6':'VARCHAR(255)',
    'Flight School 7':'VARCHAR(255)',
    'Flight School 8':'VARCHAR(255)',
    'Flight School 9':'VARCHAR(255)',
    'Flight School 10':'VARCHAR(255)',
    'Flight School 11':'VARCHAR(255)',
    'Flight School 12':'VARCHAR(255)',
    'Flight School 13':'VARCHAR(255)',
    'Flight School 14':'VARCHAR(255)',
    'Flight School 15':'VARCHAR(255)',
    'Flight School 16':'VARCHAR(255)',
    'Flight School 17':'VARCHAR(255)',
    'Flight School 18':'VARCHAR(255)',
    'Flight School 19':'VARCHAR(255)',
    'Flight School 20':'VARCHAR(255)',
    'Flight School 21':'VARCHAR(255)',
    'Disbursed Amount 1':'DOUBLE',
    'Disbursed Amount 2':'DOUBLE',
    'Disbursed Amount 3':'DOUBLE',
    'Disbursed Amount 4':'DOUBLE',
    'Disbursed Amount 5':'DOUBLE',
    'Disbursed Amount 6':'DOUBLE',
    'Disbursed Amount 7':'DOUBLE',
    'Disbursed Amount 8':'DOUBLE',
    'Disbursed Amount 9':'DOUBLE',
    'Disbursed Amount 10':'DOUBLE',
    'Disbursed Amount 11':'DOUBLE',
    'Disbursed Amount 12':'DOUBLE',
    'Disbursed Amount 13':'DOUBLE',
    'Disbursed Amount 14':'DOUBLE',
    'Disbursed Amount 15':'DOUBLE',
    'Disbursed Amount 16':'DOUBLE',
    'Disbursed Amount 17':'DOUBLE',
    'Disbursed Amount 18':'DOUBLE',
    'Disbursed Amount 19':'DOUBLE',
    'Disbursed Amount 20':'DOUBLE',
    'Disbursed Amount 21':'DOUBLE',
    'Description 1':'VARCHAR(255)',
    'Description 2':'VARCHAR(255)',
    'Description 3':'VARCHAR(255)',
    'Description 4':'VARCHAR(255)',
    'Description 5':'VARCHAR(255)',
    'Description 6':'VARCHAR(255)',
    'Description 7':'VARCHAR(255)',
    'Description 8':'VARCHAR(255)',
    'Description 9':'VARCHAR(255)',
    'Description 10':'VARCHAR(255)',
    'Description 11':'VARCHAR(255)',
    'Description 12':'VARCHAR(255)',
    'Description 13':'VARCHAR(255)',
    'Description 14':'VARCHAR(255)',
    'Description 15':'VARCHAR(255)',
    'Description 16':'VARCHAR(255)',
    'Description 17':'VARCHAR(255)',
    'Description 18':'VARCHAR(255)',
    'Description 19':'VARCHAR(255)',
    'Description 20':'VARCHAR(255)',
    'Description 21':'VARCHAR(255)'
}