raw_flight_training = {
    'id':'INT',
    'Account':'BIGINT',
    'borrower_name':'VARCHAR(50)',
    'birthday':'DATETIME',
    'School onboarding date':'DATETIME',
    'NPS (current)':'VARCHAR(5)',
    'Notes on NPS':'VARCHAR(50)',
    'Flight School':'VARCHAR(225)',
    'Unnamed: 7':'VARCHAR(50)',
    'Flight School State':'VARCHAR(5)',
    'Flight School Tier':'VARCHAR(225)',
    'Part 141 or 61 or Both':'VARCHAR(50)',
    'Flight School Program':'VARCHAR(225)',
    'Flight School Program Total Hours':'INT',
    'Flight Training 0 Hours':'DATETIME',
    'Flight Training 40/50-hour Milestone':'DATETIME',
    'Flight Training 70/120-hour Milestone':'DATETIME',
    'Flight Training 170/180-hour Milestone':'DATETIME',
    'Flight Training 230-hour Milestone':'DOUBLE',
    'PPL':'VARCHAR(5)',
    'IFR':'VARCHAR(5)',
    'COMM SE':'VARCHAR(5)',
    'COMM Multi':'VARCHAR(5)',
    'CFI':'VARCHAR(5)',
    'CFII':'VARCHAR(5)',
    'MEI':'VARCHAR(5)',
    'ATP':'VARCHAR(5)',
    'Certificates based on FAA':'TEXT',
    'Other Certificates based on FAA':'VARCHAR(225)',
    'Date latest Cert was issued by FAA':'DATETIME',
    'Employment':'VARCHAR(225)',
    'Notes on flight training':'VARCHAR(225)'
}