dim_payment_schedule = {
    'id':'INT',
    'Account':'BIGINT',
    'Payment Schedule 1 Start Date':'DATETIME',
    'Payment Schedule 1 End Date':'DATETIME',
    'Payment Schedule 2 Start Date':'DATETIME',
    'Payment Schedule 2 End Date':'DATETIME',
    'Payment Schedule 3 Start Date':'DATETIME',
    'Payment Schedule 3 End Date':'DATETIME',
    'Payment Schedule 4 Start Date':'DATETIME',
    'Payment Schedule 4 End Date':'DATETIME',
    'Payment Schedule 1 Amount':'DOUBLE',
    'Payment Schedule 2 Amount':'DOUBLE',
    'Payment Schedule 3 Amount':'DOUBLE',
    'Payment Schedule 4 Amount':'DOUBLE',
    'Payment Schedule 1 Note Rate':'DOUBLE',
    'Payment Schedule 2 Note Rate':'DOUBLE',
    'Payment Schedule 3 Note Rate':'DOUBLE',
    'Payment Schedule 4 Note Rate':'DOUBLE',
    'Deferred Schedule Start Date':'DATETIME',
    'Deferred Schedule End Date':'DATETIME',
    'Interest Only Schedule Start Date':'DATETIME',
    'Interest Only Schedule End Date':'DATETIME',
    'P&I Schedule Start Date':'DATETIME',
    'P&I Schedule End Date':'DATETIME'
}